### ISSUE TITLE
Extend the app

### ISSUE THREAD

**Issue by amoraitis** [amoraitis/AuebUnofficial#21]
###### Roadmap
- [x] AppSettings
- [x] EclassUser(for saving the login info localy)
- [ ] School program
    - [ ] Day2Day program of the school
    - [ ] Exams program
    - [ ] Cron job(for automated update of its program throught the school website)

--Add More --
###### Roadmap

- [ ] App Homepage
    - [x] aueb.gr webview
    - [ ] Facebook feed button
    - [ ] Twitter hashtags button

- [ ] RSS announcements page

- [ ] Day-to-day and exams program page

- [ ] Information for each school page

- [ ] EclassApi integration
    - [ ] Login page
    - [ ] Announcements page(also features implemented in UWP like copy-open link-print(?))

- [ ] Interaction buttons
    - [ ] Review button
    - [ ] About page

--Add More --
